---
- name: "[RH] Install nginx with epel-release"
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - epel-release
      - nginx
  register: nginx_installed_rh
  notify: Enable nginx
  when: ansible_os_family|lower == "redhat"

- name: "[Debian] Install nginx"
  apt:
    update_cache: yes
    name: nginx
  register: nginx_installed_debian
  notify: Enable nginx
  when: ansible_os_family|lower == "debian"

- name: "[RH] [NGINX] Add index file"
  copy:
    src: "{{ item }}"
    dest: "{{ html_destinaton_folder }}/{{ item }}"
    mode: 0644
    owner: nginx
    group: nginx
  loop:
    - index.html
  when: ansible_os_family|lower == "redhat"

- name: "[Debian] [NGINX] Add index file"
  copy:
    src: "{{ item }}"
    dest: "{{ html_destinaton_folder }}/{{ item }}"
    mode: 0644
    owner: www-data
    group: www-data
  loop:
    - index.html
  when: ansible_os_family|lower == "debian"

  